mock_estoque = [
    {'id': 1, 'nome': 'Paracetamol', 'quantidade': 150},
    {'id': 2, 'nome': 'Dipirona', 'quantidade': 120},
    {'id': 3, 'nome': 'Amoxicilina', 'quantidade': 80},
    {'id': 4, 'nome': 'Ibuprofeno', 'quantidade': 110},
    {'id': 5, 'nome': 'Omeprazol', 'quantidade': 95},
    {'id': 6, 'nome': 'Loratadina', 'quantidade': 75},
    {'id': 7, 'nome': 'Sinvastatina', 'quantidade': 130},
    {'id': 8, 'nome': 'Metformina', 'quantidade': 180},
    {'id': 9, 'nome': 'Atenolol', 'quantidade': 60},
    {'id': 10, 'nome': 'Captopril', 'quantidade': 140},
    {'id': 11, 'nome': 'Clonazepam', 'quantidade': 45},
    {'id': 12, 'nome': 'Buscopan', 'quantidade': 200},
    {'id': 13, 'nome': 'Rivotril', 'quantidade': 30},
    {'id': 14, 'nome': 'Insulina NPH', 'quantidade': 50},
    {'id': 15, 'nome': 'Aspirina', 'quantidade': 250},
    {'id': 16, 'nome': 'Torsilax', 'quantidade': 70},
    {'id': 17, 'nome': 'Losartana', 'quantidade': 115},
    {'id': 18, 'nome': 'Prednisona', 'quantidade': 85},
    {'id': 19, 'nome': 'Novalgina', 'quantidade': 160},
    {'id': 20, 'nome': 'Cefalexina', 'quantidade': 90},
    {'id': 21, 'nome': 'Nimesulida', 'quantidade': 105},
    {'id': 22, 'nome': 'Dexametasona', 'quantidade': 55},
    {'id': 23, 'nome': 'Diclofenaco', 'quantidade': 170},
    {'id': 24, 'nome': 'Neosoro', 'quantidade': 190},
    {'id': 25, 'nome': 'Dramin', 'quantidade': 100},
    {'id': 26, 'nome': 'Glibenclamida', 'quantidade': 125},
    {'id': 27, 'nome': 'Claritromicina', 'quantidade': 40},
    {'id': 28, 'nome': 'Ranitidina', 'quantidade': 135},
    {'id': 29, 'nome': 'Fluoxetina', 'quantidade': 78},
    {'id': 30, 'nome': 'Sertralina', 'quantidade': 65},
    {'id': 31, 'nome': 'Tylenol', 'quantidade': 145},
    {'id': 32, 'nome': 'Puran T4', 'quantidade': 92},
    {'id': 33, 'nome': 'Plasil', 'quantidade': 118},
    {'id': 34, 'nome': 'Allegra', 'quantidade': 82},
    {'id': 35, 'nome': 'Furosemida', 'quantidade': 155},
    {'id': 36, 'nome': 'Hidroclorotiazida', 'quantidade': 175},
    {'id': 37, 'nome': 'Escitalopram', 'quantidade': 68},
    {'id': 38, 'nome': 'Anlodipino', 'quantidade': 108},
    {'id': 39, 'nome': 'Bromazepam', 'quantidade': 42},
    {'id': 40, 'nome': 'Minoxidil', 'quantidade': 58},
    {'id': 41, 'nome': 'Propranolol', 'quantidade': 122},
    {'id': 42, 'nome': 'Albendazol', 'quantidade': 165},
    {'id': 43, 'nome': 'Cetoprofeno', 'quantidade': 73},
    {'id': 44, 'nome': 'Azitromicina', 'quantidade': 88},
    {'id': 45, 'nome': 'Pantoprazol', 'quantidade': 98},
    {'id': 46, 'nome': 'Advil', 'quantidade': 132},
    {'id': 47, 'nome': 'Resfenol', 'quantidade': 148},
    {'id': 48, 'nome': 'Vitamina C', 'quantidade': 210},
    {'id': 49, 'nome': 'Dorflex', 'quantidade': 195},
    {'id': 50, 'nome': 'Benegrip', 'quantidade': 112}
]